import { Toaster } from "react-hot-toast";
import "./globals.css";
import Nav from "@/components/Nav";
import Provider from "@/components/Provider";

export const metadata = {
  title: "Expensor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Nav />
          <Toaster />
          <main className="app">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
